### PR TITLE
Fix i18n locale lookup

### LINKED ISSUE #29: Color chart for CDay Seen/Scanned isn't visually giving the expected info
The color chart shows in blue the scanned value and in green the seen value. Thus an ideal setup would show a half blue half green chart, which isn't really the best style tmo.
It would make more sense to show in green the scanned value, and like in orange or red the (seen-scanned) value -> giving a full green chart when all seens are scanned

Also, side note, it would be nice to also have on this panel the Shiny rate of this Cday Pokémon for the period.

Capture d’écran 2020-09-20 à 15 21 54

### LINKED ISSUE #30: Support mega in raids

### PR DESCRIPTION
**Pull request by versx**
Parses locales correctly when passing replacement arguments  
Fix #29 
Fix #30
Fixes issue with local icon repos

image

### CODE REVIEW

File: src/services/locale.js [hunk 1]
```diff
@@ -1,251 +1,254 @@
...
+            } else {
+                string = pokedex[info.pokemon_id];
+            }
+            if (info.shiny) {
+                string += ' (Shiny)';
+            }
+            return string;
         } else {
-            string = pokedex[info.pokemon_id];
+            return i18n('quest_reward_' + id);
```
Comment (versx) [inline src/services/locale.js]:
```suggestion
            string = pokedex[info.pokemon_id];
```

**Review by Petap0w — COMMENTED** [review]
I would suggest instead:
```
                  data: [(result.data.stats.total-result.data.stats.with_iv) || 0, result.data.stats.with_iv || 0],
                  backgroundColor: [
                      'red',
                      'green'
                  ],
                  label: 'Seen'
```
